# Generated by Django 3.2.3 on 2021-07-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_joinrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='asker',
            new_name='user',
        ),
    ]
