# Generated by Django 3.2.3 on 2021-08-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_last_logged_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_logged_out',
            new_name='last_logged_in',
        ),
    ]
