# Generated by Django 3.2.3 on 2021-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_placetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
