# Generated by Django 3.2.3 on 2021-07-12 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_joined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
