# Generated by Django 3.2.3 on 2021-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationbubble',
            name='place_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
