# Generated by Django 3.2.3 on 2021-09-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_locationbubble_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='added_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
    ]
