# Generated by Django 3.2.3 on 2021-07-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification_user_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='join_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.joinrequest'),
        ),
    ]
