# Generated by Django 3.2.3 on 2021-09-06 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification_added_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='added_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_place_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
