# Generated by Django 3.2.3 on 2021-07-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification_join_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='now_private',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='now_public',
            field=models.BooleanField(null=True),
        ),
    ]
