# Generated by Django 3.2.3 on 2021-08-17 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210721_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBubble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hours', models.FloatField()),
                ('minutes', models.FloatField()),
                ('transportation', models.CharField(choices=[('bike', 'bike'), ('transit', 'transit'), ('walk', 'walk'), ('car', 'car')], max_length=7)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
