# Generated by Django 3.2.3 on 2021-09-11 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_notification_added_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlaceType',
        ),
    ]
