# Generated by Django 3.2.3 on 2021-08-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_locationbubble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationbubble',
            name='hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='locationbubble',
            name='minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
