# Generated by Django 3.2.3 on 2021-10-09 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210911_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
