# Generated by Django 3.2.3 on 2021-10-15 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211015_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='voted_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_place_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
