# Generated by Django 3.2.3 on 2021-08-22 02:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_intersection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None), size=None),
        ),
    ]
