# Generated by Django 3.2.3 on 2021-08-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_intersection_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationbubble',
            name='region',
            field=models.CharField(choices=[('asia', 'asia'), ('africa', 'africa'), ('australia', 'australia'), ('britishisles', 'britishisles'), ('central_america', 'central_america'), ('easterneurope', 'easterneurope'), ('northamerica', 'northamerica'), ('south_america', 'south_america'), ('westcentraleurope', 'westcentraleurope')], default='britishisles', max_length=17),
        ),
    ]
